services:
  catalogdb:
    image: 'postgres:latest'

  basketdb:
    image: 'postgres:latest'

  orderdb:
    image: 'mcr.microsoft.com/mssql/server'

  distributedcache:
    image: redis

  messagebroker:
    image: rabbitmq

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

volumes:
    postgres_catalog:
    postgres_basket:



